# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ceatetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='person',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
