# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20160530_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ceatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
