# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20160530_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ceatetime',
            new_name='createtime',
        ),
    ]
